---
- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: Install the version  of package "nginx" and allow potential downgrades
  ansible.builtin.apt:
    name: nginx
    state: present
    allow_downgrade: yes

- name: Install latest version of package "keepalived" and allow potential downgrades
  ansible.builtin.apt:
    name: keepalived
    state: present
    allow_downgrade: yes

- name: 拷贝nginx配置文件
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: 拷贝keepalived配置文件       
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf

- name: 拷贝nginx健康检查脚本
  copy: src=check_nginx.sh dest=/etc/keepalived/ mode=u+x

- name: 启动服务
  systemd: name={{ item }} state=restarted enabled=yes daemon_reload=yes
  with_items:
    - nginx
    - keepalived
