---
- name: create temp directory
  file: dest={{ tmp_dir }} state=directory

- name: extract docker binary tgz file
  unarchive: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "{{ software_dir }}/docker-*.tgz"

- name: copy docker bin files to /user/bin
  shell: cp -rf {{ tmp_dir }}/docker/* /usr/bin/

- name: copy docker service file
  copy: src=docker.service dest=/usr/lib/systemd/system/

- name: mkdir /etc/docker
  file: dest=/etc/docker state=directory

- name: configure docker daemon
  copy: src=daemon.json dest=/etc/docker/daemon.json

- name: start docker
  systemd: name=docker state=restarted enabled=yes daemon_reload=yes

- name: show docker info
  shell: docker info
  register: docker 
- debug: var=docker.stdout_lines
