---
# 这个剧本在所有节点上运行
- name: Update /etc/fstab
  lineinfile:
    dest: /etc/fstab
    regexp: ".*swap"
    line: ""

- name: Swap Off
  shell: setenforce 0 ; swapoff -a

- name: Set timezone to Shanghai
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: Edit hosts
  template: src=hosts.j2 dest=/etc/hosts 

#- name: 同步系统时间
#  yum: name=ntpdate state=present
#- name: 同步系统时间
#  shell: ntpdate time.windows.com

